// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './../pages/__root'
import { Route as WebrtcImport } from './../pages/webrtc'
import { Route as IndexImport } from './../pages/index'
import { Route as WebrtcVideochatImport } from './../pages/webrtc/videochat'
import { Route as WebrtcMsgchatImport } from './../pages/webrtc/msgchat'
import { Route as WebrtcMediaImport } from './../pages/webrtc/media'
import { Route as WebrtcGoodbyeImport } from './../pages/webrtc/goodbye'
import { Route as WebrtcRoomCodeRoomNameImport } from './../pages/webrtc/$roomCode.$roomName'

// Create/Update Routes

const WebrtcRoute = WebrtcImport.update({
  path: '/webrtc',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const WebrtcVideochatRoute = WebrtcVideochatImport.update({
  path: '/videochat',
  getParentRoute: () => WebrtcRoute,
} as any)

const WebrtcMsgchatRoute = WebrtcMsgchatImport.update({
  path: '/msgchat',
  getParentRoute: () => WebrtcRoute,
} as any)

const WebrtcMediaRoute = WebrtcMediaImport.update({
  path: '/media',
  getParentRoute: () => WebrtcRoute,
} as any)

const WebrtcGoodbyeRoute = WebrtcGoodbyeImport.update({
  path: '/goodbye',
  getParentRoute: () => WebrtcRoute,
} as any)

const WebrtcRoomCodeRoomNameRoute = WebrtcRoomCodeRoomNameImport.update({
  path: '/$roomCode/$roomName',
  getParentRoute: () => WebrtcRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/webrtc': {
      preLoaderRoute: typeof WebrtcImport
      parentRoute: typeof rootRoute
    }
    '/webrtc/goodbye': {
      preLoaderRoute: typeof WebrtcGoodbyeImport
      parentRoute: typeof WebrtcImport
    }
    '/webrtc/media': {
      preLoaderRoute: typeof WebrtcMediaImport
      parentRoute: typeof WebrtcImport
    }
    '/webrtc/msgchat': {
      preLoaderRoute: typeof WebrtcMsgchatImport
      parentRoute: typeof WebrtcImport
    }
    '/webrtc/videochat': {
      preLoaderRoute: typeof WebrtcVideochatImport
      parentRoute: typeof WebrtcImport
    }
    '/webrtc/$roomCode/$roomName': {
      preLoaderRoute: typeof WebrtcRoomCodeRoomNameImport
      parentRoute: typeof WebrtcImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  IndexRoute,
  WebrtcRoute.addChildren([
    WebrtcGoodbyeRoute,
    WebrtcMediaRoute,
    WebrtcMsgchatRoute,
    WebrtcVideochatRoute,
    WebrtcRoomCodeRoomNameRoute,
  ]),
])
